### ISSUE TITLE
How to add more infor when calling a connecting

### ISSUE THREAD

**Issue by buiminhhuy** [ShengHuaWu/StompClient#1]
http://jmesnil.net/stomp-websocket/doc/
example:
    var headers = {
      login: 'mylogin',
      passcode: 'mypasscode',
      // additional header
      'client-id': 'my-client-id'
    };
    client.connect(headers, connectCallback);

**Comment by ShengHuaWu** [comment]
Please use `setValue(value: String, forHeaderField field: String)` method of _StompClient_ to add custom headers for websocket connection.
However, it's possible to pass custom parameters for a _STOMP_ subscription via `subscribe(destination: String, parameters: [String : String]?)` method.
